import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import Footer from "@/component/Footer/Footer";
import AuthProvider from "@/contexts/AuthProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-inter",
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-poppins",
});

export const metadata = {
	title: "SuperShop",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body
				className={`${inter.variable} ${poppins.variable}  antialiased`}
			>
				<AuthProvider>
					<Navbar />
					{children}
					<Toaster />
				</AuthProvider>
				<Footer />
			</body>
		</html>
	);
}
